### ISSUE TITLE
Do not set left value

### ISSUE THREAD

**Issue by andwhy** [vadymmarkov/MARKRangeSlider#5]
If i set left value first and then right, left value will still be not set. Code below works but if i set left value first it will be 1

```
_ageSlider.minimumValue = 14.0;
_ageSlider.maximumValue = 99.0;
_ageSlider.rightValue = 28.0;
_ageSlider.leftValue = 18.0;
_ageSlider.minimumDistance = 1.0;

[_ageSlider addTarget:self
               action:@selector(rangeSliderValueDidChange:)
     forControlEvents:UIControlEventValueChanged];

[self updateRangeText];
```

**Comment by vadymmarkov** [comment]
@andwhy Actually, everything works as expected if you do setup in the following order.

``` objc
    self.rangeSlider.maximumValue = 99.0;
    self.rangeSlider.minimumValue = 14.0;
    self.rangeSlider.rightValue = 28.0;
    self.rangeSlider.leftValue = 18.0;
    self.rangeSlider.minimumDistance = 1.0;
```

That's because of validations that max value should be > than min, right > left, etc. Default values are between 0 and 1, so it causes conflicts. Probably, I have to update readme, but if you find it not too obvious and have some good vision of how to solve it in the better way, just tell me. I'm open for it.

**Comment by pronebird** [comment]
Yeah I stumbled upon the same issue today. I'll sleep on this issue and maybe come up with something later. As an option to set min/max range at once -setRangeWithMinValue:min maxValue:max

**Comment by vadymmarkov** [comment]
Should be fixed here https://github.com/vadymmarkov/MARKRangeSlider/pull/19
